---
apiVersion: v1
kind: ConfigMap
metadata:
  name: wmapp-config
data:
  wm.mysqlCloudHost: "wmappdatabasesvc:3306"
  wm.mysqlCloudUsername: "root"
---
apiVersion: v1
kind: Secret
metadata:
  name: mysqlsecret
  labels:
    app: wm-app
data:
  MYSQL_ROOT_PASSWORD: d21hcHBhZG1pbg==

# wmappadmin
