---
apiVersion: v1
kind: ConfigMap
metadata:
  name: wmapp-config-APP_NAME
data:
  wm.mysqlCloudHost: "wmappdatabasesvc-APP_NAME:3306"
  wm.mysqlCloudUsername: "root"
---
apiVersion: v1
kind: Secret
metadata:
  name: mysqlsecret-APP_NAME
  labels:
    app: wm-app-APP_NAME
data:
  MYSQL_ROOT_PASSWORD: d21hcHBhZG1pbg==

# wmappadmin
