---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: wmapp-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    #    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  tls:
  - secretName: MYTLS_SECRET
  rules:
    - host: testapp.com
      http:
       paths:
       - path: /MY_APPLICATION/*
         backend:
           serviceName: webservice-APP_NAME
           servicePort: 8080

