---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: azure-devops-deploy-role
rules:
- apiGroups: ["", "extensions", "apps"]
  resources: ["deployments", "replicasets", "pods", "services", "secrets", "configmaps", "cronjobs", "daemonsets", "horizontalpodautoscalers", "ingresses", "namespaces", "nodes", "persistentvolumeclaims", "secrets", "statefulsets", "storageclasses"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: azure-devops-deploy-manager
subjects:
- kind: Group
  name: system:serviceaccounts
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: azure-devops-deploy-role
  apiGroup: rbac.authorization.k8s.io

