name: wavemaker cicd
trigger:
  branches:
    include:
    - prod
    - UAT
    exclude:
    - master


#pr:
 # branches:
   # include:
  #  - master
   # exclude:
   # - prod
   # - UAT
variables: 
  ## Add this under variables section in the pipeline
  image_repository: $(repository_name)
  azureContainerRegistry: $(acr_service_name)
  aks_service: $(aks_service_name)
  image_registry: $(acr_registry)
  subcription_service: $(az_subcription_service)
  storage_account: $(storage_account_name)
  MAVEN_CACHE_FOLDER: $(Pipeline.Workspace)/.m2/repository
  MAVEN_OPTS: '-Dmaven.repo.local=$(MAVEN_CACHE_FOLDER)'
  uat_build_profile: $(uat_maven_build_profile)
  prod_build_profile: $(prod_maven_build_profile)
  webapp_replicas: $(no_of_webapp_repicas)
  database_container: $(default_database_container)
  PROD_branch_namespace: $(prod_namespace)
  UAT_branch_namespace: $(uat_namespace)
  application_context: $(application_name)
  uat_cdn_url: $(uat_env_cdn_url)
  prod_cdn_url: $(prod_env_cdn_url)
  uat_blob: $(uat_container_blob)
  prod_blob: $(prod_container_blob)
  uat_hostname: $(uat_env_hostname)
  tls_secretname: $(tls_secret_name)
  project_name: $(unique_name_for_application)
  prod_hostname: $(prod_env_host_name)
  website_private_key: $(website_private_key_filename)
  website_bundle_crt: $(website_bundle_certificate_filename)
pool:
    vmImage: 'Ubuntu-16.04'
stages:
- stage: build_and_deploy
  jobs:
  - job: maven_build_and_docker_build
    displayName: maven build and docker image build
    steps:
      - task: Cache@2
        inputs:
          key: 'maven | "$(Agent.OS)" | **/pom.xml'
          restoreKeys: |
            maven | "$(Agent.OS)"
            maven
          path: $(MAVEN_CACHE_FOLDER)
        displayName: Cache Maven local repo
      - script: |
            wget https://nodejs.org/dist/v10.12.0/node-v10.12.0-linux-x64.tar.gz
            mkdir $(Build.SourcesDirectory)/node
            tar -xzf node-v10.12.0-linux-x64.tar.gz -C $(Build.SourcesDirectory)/node
            sudo rm -f /usr/local/bin/node
            sudo rm -f /usr/local/bin/npm
            sudo ln -s $(Build.SourcesDirectory)/node/node-v10.12.0-linux-x64/bin/node /usr/local/bin/node
            sudo ln -s $(Build.SourcesDirectory)/node/node-v10.12.0-linux-x64/bin/npm  /usr/local/bin/npm
            sudo chown -R root:root $(Build.SourcesDirectory)/node
        displayName: prerequisites installation
      - script: |
            mvn clean install -Pdeployment
        displayName: maven build on PR
        condition: and(succeeded(), eq(variables['Build.Reason'], 'PullRequest'))

      - script: |
            mvn clean install -P$(uat_build_profile) -Dcdn-url=$(uat_cdn_url)/$(Build.BuildId)/ng-bundle/
            mkdir static_content
            unzip ./target/ui-artifact.zip -d static_content/
        displayName: maven build on UAT branch
        condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/UAT'))

      - script: |
            mvn clean install -P$(prod_build_profile) -Dcdn-url=$(prod_cdn_url)/$(Build.BuildId)/ng-bundle/
            mkdir static_content
            unzip ./target/ui-artifact.zip -d static_content/
        displayName: maven build on prod branch
        condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/prod'))

      - task: AzureCLI@2
        displayName: uploading static content
        condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/UAT'))
        inputs:
          azureSubscription: $(subcription_service)
          scriptType: bash
          scriptLocation: inlineScript
          inlineScript: |
            az storage blob upload-batch -s ./static_content/ -d $(uat_blob) --destination-path $(Build.BuildId) --account-name $(storage_account)
      
      - task: AzureCLI@2
        displayName: uploading static content
        condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/prod'))
        inputs:
          azureSubscription: $(subcription_service)
          scriptType: bash
          scriptLocation: inlineScript
          inlineScript: |
            az storage blob upload-batch -s ./static_content/ -d $(prod_blob) --destination-path $(Build.BuildId) --account-name $(storage_account)

      - task: Docker@2
        displayName: Login to ACR
        condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
        inputs:
          command: login
          containerRegistry: $(azureContainerRegistry)
      - task: Docker@2
        displayName: build and Push image
        condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
        inputs:
          containerRegistry: |
            $(azureContainerRegistry)
          repository: $(image_repository)
          command: buildAndPush
          tags: |
            $(Build.BuildId)

  - job: AKS_deployment_to_UAT
    dependsOn: maven_build_and_docker_build
    displayName: deploy to AKS from UAT
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/UAT'))
    steps:
    - script: |
          sed -i '/replicas/  s/1/$(webapp_replicas)/g' k8s-manifestfiles/wm_app_webapp.yml
          sed -i '/image/   s/CONTAINER_IMAGE/$(image_registry)\/$(image_repository):tag/g' k8s-manifestfiles/wm_app_webapp.yml
          sed -i '/path/   s/MY_APPLICATION\/\*/$(application_context)\/\*/g' k8s-manifestfiles/wm_app_nginx_ingress_service.yml
          sed -i '/host/   s/testapp.com/$(uat_hostname)/g' k8s-manifestfiles/wm_app_nginx_ingress_service.yml
          sed -i '/secretName/  s/MYTLS_SECRET/$(tls_secretname)/g' k8s-manifestfiles/wm_app_nginx_ingress_service.yml
      displayName: preparing manifestfiles
    - script: |
          sed -i 's/APP_NAME/$(project_name)/g' k8s-manifestfiles/*
      displayName: preparing app deployments files
    - task: DownloadSecureFile@1
      name: websitebundle
      displayName: 'Download website certificate'
      inputs:
        secureFile: '$(website_bundle_crt)'
    - task: DownloadSecureFile@1
      name: websiteprivatekey
      displayName: 'Download website private key'
      inputs:
        secureFile: '$(website_private_key)'
    - task: Kubernetes@1
      displayName: creating TLS secret in UAT env
      inputs:
        connectionType: Kubernetes Service Connection
        kubernetesServiceEndpoint: $(aks_service)
        command: create
        arguments: secret tls $(tls_secretname)  --namespace $(UAT_branch_namespace)  --key $(websiteprivatekey.secureFilePath)  --cert $(websitebundle.secureFilePath)

    - task: Kubernetes@1
      displayName: creating TLS secret in default namespace observability ingress service SSL
      inputs:
        connectionType: Kubernetes Service Connection
        kubernetesServiceEndpoint: $(aks_service)
        command: create
        arguments: secret tls $(tls_secretname)  --namespace default  --key $(websiteprivatekey.secureFilePath)  --cert $(websitebundle.secureFilePath)
      continueOnError: true

    - task: KubernetesManifest@0
      condition: eq(variables['database_container'], 'yes')
      displayName: Deploy database  to UAT branch env
      inputs:
        kubernetesServiceConnection: $(aks_service)
        namespace: $(UAT_branch_namespace)
        manifests: k8s-manifestfiles/database_statefulset.yml
        
    - task: KubernetesManifest@0
      displayName: Deploy only app container to UAT branch
      inputs:
        kubernetesServiceConnection: $(aks_service)
        namespace: $(UAT_branch_namespace)
        manifests: k8s-manifestfiles/wm_app_webapp.yml
        containers: |
          $(image_registry)/$(image_repository):$(Build.BuildId)
    - task: KubernetesManifest@0
      displayName: Deploy application config and secrets to UAT branch env
      inputs:
        kubernetesServiceConnection: $(aks_service)
        namespace: $(UAT_branch_namespace)
        manifests: k8s-manifestfiles/wm_app_config_and_secret.yml
    - task: KubernetesManifest@0
      displayName: Deploy horizantal pod autoscale to UAT branch env
      inputs:
        kubernetesServiceConnection: $(aks_service)
        namespace: $(UAT_branch_namespace)
        manifests: k8s-manifestfiles/wm_app_hpa.yml
    - task: KubernetesManifest@0
      displayName: Deploy ingress service to UAT branch env
      inputs:
        kubernetesServiceConnection: $(aks_service)
        namespace: $(UAT_branch_namespace)
        manifests: k8s-manifestfiles/wm_app_nginx_ingress_service.yml
        

  - job: AKS_deployment_to_prod
    dependsOn: maven_build_and_docker_build
    displayName: deploy to AKS from prod
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/prod'))
    steps:
    - script: |
          sed -i '/replicas/  s/1/$(webapp_replicas)/g' k8s-manifestfiles/wm_app_webapp.yml
          sed -i '/image/   s/CONTAINER_IMAGE/$(image_registry)\/$(image_repository):tag/g' k8s-manifestfiles/wm_app_webapp.yml
          sed -i '/path/   s/MY_APPLICATION\/\*/$(application_context)\/\*/g' k8s-manifestfiles/wm_app_nginx_ingress_service.yml
          sed -i '/host/   s/testapp.com/$(prod_hostname)/g' k8s-manifestfiles/wm_app_nginx_ingress_service.yml
          sed -i '/secretName/  s/MYTLS_SECRET/$(tls_secretname)/g' k8s-manifestfiles/wm_app_nginx_ingress_service.yml
      displayName: preparing webapp replicas and container image name
    - script: |
          sed -i 's/APP_NAME/$(project_name)/g' k8s-manifestfiles/*
      displayName: preparing manifestfiles
    - task: DownloadSecureFile@1
      name: websitebundle
      displayName: 'Download website certificate'
      inputs:
        secureFile: 'website-bundle.crt'
    - task: DownloadSecureFile@1
      name: websiteprivatekey
      displayName: 'Download website private key'
      inputs:
        secureFile: 'website.key'
    - task: Kubernetes@1
      displayName: creating TLS secret in prod env
      inputs:
        connectionType: Kubernetes Service Connection
        kubernetesServiceEndpoint: $(aks_service)
        command: create
        arguments: secret tls $(tls_secretname)  --namespace $(PROD_branch_namespace)  --key $(websiteprivatekey.secureFilePath)  --cert $(websitebundle.secureFilePath)
      continueOnError: true 

    - task: KubernetesManifest@0
      condition: eq(variables['database_container'], 'yes')
      displayName: Deploy database and application container to PROD branche
      inputs:
        kubernetesServiceConnection: $(aks_service)
        namespace: $(PROD_branch_namespace)
        manifests: k8s-manifestfiles/database_statefulset.yml
        
    - task: KubernetesManifest@0
      displayName: Deploy application container to PROD branch
      inputs:
        kubernetesServiceConnection: $(aks_service)
        namespace: $(PROD_branch_namespace)
        manifests: k8s-manifestfiles/wm_app_webapp.yml
        containers: |
          $(image_registry)/$(image_repository):$(Build.BuildId)
          
    - task: KubernetesManifest@0
      displayName: Deploying application congig and secrets to PROD branch
      inputs:
        kubernetesServiceConnection: $(aks_service)
        namespace: $(PROD_branch_namespace)
        manifests: k8s-manifestfiles/wm_app_config_and_secret.yml
    - task: KubernetesManifest@0
      displayName: Deploy application horizantal pod autoscaler to PROD branch
      inputs:
        kubernetesServiceConnection: $(aks_service)
        namespace: $(PROD_branch_namespace)
        manifests: k8s-manifestfiles/wm_app_hpa.yml
    - task: KubernetesManifest@0
      displayName: Deploy application ingress service to PROD branch
      inputs:
        kubernetesServiceConnection: $(aks_service)
        namespace: $(PROD_branch_namespace)
        manifests: k8s-manifestfiles/wm_app_nginx_ingress_service.yml
        

